apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
  name: nack
  namespace: argocd
spec:
  destination:
    namespace: nack
    server: 'https://kubernetes.default.svc'
  source:
    path: nack
    repoURL: 'https://github.com/pipekit/aks-argo-workflows.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=background
      - CreateNamespace=true
