apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wf-cluster-role
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - workflowtaskresults
    verbs:
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wf-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: wf-cluster-role
subjects:
- kind: ServiceAccount
  name: workflows
  namespace: workflows
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: workflows
  namespace: workflows
