kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
apiVersion: v1
data:
  ui.bannercontent: "Security Goose says: This is AKS-Test. Should you be here? HONK!"
  statusbadge.enabled: "true"
  ui.bannerpermanent: "true"

  resource.compareoptions: |
    ignoreResourceStatusField: all
  resource.customizations: |
    admissionregistration.k8s.io/MutatingWebhookConfiguration:
      ignoreDifferences: |
        jsonPointers:
        - /webhooks/0/clientConfig/caBundle
  resource.customizations.ignoreDifferences.all: |
    jsonPointers:
    - /metadata/annotations/karpenter.sh~1do-not-disrupt
  # The metadata.label key name where Argo CD injects the app name as a tracking label (optional).
  # Tracking labels are used to determine which resources need to be deleted when pruning.
  # If omitted, Argo CD injects the app name into the label: 'app.kubernetes.io/instance'
  application.instanceLabelKey: pipekit.io/appname
