apiVersion: v1
kind: Secret
metadata:
  name: eks-argo-workflows
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  name: Pipekit EKS Argo Workflows
  url: https://github.com/pipekit/aks-argo-workflows.git

