apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: argocd-repo-server
          resources:
            requests:
              cpu: 85m
              memory: 65Mi
