apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: stream
spec:
  templates:
    - name: create
      inputs:
        parameters:
          - name: stream
      resource:
        action: create
        setOwnerReference: true
        manifest: |
          apiVersion: jetstream.nats.io/v1beta2
          kind: Stream
          metadata:
            name: "{{inputs.parameters.stream}}"
          spec:
            name: "{{inputs.parameters.stream}}"
            subjects: ["{{inputs.parameters.stream}}.*"]
            storage: memory
            retention: workqueue
            maxAge: 24h
    - name: delete
      inputs:
        parameters:
          - name: stream
      resource:
        action: delete
        manifest: |
          apiVersion: jetstream.nats.io/v1beta2
          kind: Stream
          metadata:
            name: "{{inputs.parameters.stream}}"
